[package]
name = "wt-proto"
version = "0.1.0"
edition = "2021"

[features]
default = ["h3"]
h3 = ["coding"]
coding = [] # Only contains the VarInt and its extensions

[dependencies]
quinn = {"workspace" = true }
thiserror = {"workspace" = true}
bytes = {"workspace" = true}
async-trait = {"workspace" = true}
tracing = {"workspace" = true}
